version: '3'
services:
  db:
      image: 'postgres:latest'
      environment:
          POSTGRES_PASSWORD: security#4321
          POSTGRES_USER: adm
          POSTGRES_DB: tasks
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
